name: Test

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
    branches:
      - 'main'

jobs:
  try:
    name: try
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup aws-aurora-cluster-snapshot
        uses: ./
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          prefix: backup
